steps:
  # Reservations
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "url-to-docker-image/reservations/productions",
        "-f",
        "apps/reservations/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "url-to-docker-image/reservations/productions"]

  # Auth
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "url-to-docker-image/auth/productions",
        "-f",
        "apps/auth/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "url-to-docker-image/auth/productions"]

  # Payments
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "url-to-docker-image/payments/productions",
        "-f",
        "apps/payments/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "url-to-docker-image/payments/productions"]

  # Notifications
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "url-to-docker-image/notifications/productions",
        "-f",
        "apps/notifications/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "url-to-docker-image/notifications/productions"]
